### ISSUE TITLE
Running kernelgateway produces: ImportError: No module named nbformat

### ISSUE THREAD

**Issue by guiwork** [jupyter/kernel_gateway#121]
Tried to follow installation instructions using pip. Building on Ubuntu 14.04 machine with Python 2.7.6 and pip 1.5.4. I'm wondering if this has to do with zmq as the first try at installing I did not have the header files on my system which I later installed (libzmq-dev).

```
administrator@etc04:~/kernel_gateway$ sudo pip install jupyter_kernel_gateway
Downloading/unpacking jupyter-kernel-gateway
  Downloading jupyter_kernel_gateway-0.4.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): jupyter-core>=4.0,<5.0 in /usr/local/lib/python2.7/dist-packages (from jupyter-kernel-gateway)
Requirement already satisfied (use --upgrade to upgrade): jupyter-client>=4.0,<5.0 in /usr/local/lib/python2.7/dist-packages (from jupyter-kernel-gateway)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.7,<3.0 in /usr/local/lib/python2.7/dist-packages (from jupyter-kernel-gateway)
Requirement already satisfied (use --upgrade to upgrade): notebook>=4.0,<5.0 in /usr/local/lib/python2.7/dist-packages (from jupyter-kernel-gateway)
Installing collected packages: jupyter-kernel-gateway
Successfully installed jupyter-kernel-gateway
Cleaning up...
```

```
administrator@etc04:~/kernel_gateway$ jupyter kernelgateway
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-kernelgateway", line 7, in <module>
    from kernel_gateway import launch_instance
  File "/usr/local/lib/python2.7/dist-packages/kernel_gateway/__init__.py", line 4, in <module>
    from .gatewayapp import launch_instance
  File "/usr/local/lib/python2.7/dist-packages/kernel_gateway/gatewayapp.py", line 6, in <module>
    import nbformat
ImportError: No module named nbformat
administrator@etc04:~/kernel_gateway$
```

**Comment by parente** [comment]
Looks like we have a missing prereq requirement. Odd considering I thought notebook required nbformat.

**Comment by parente** [comment]
Can you try upgrading your version of `pip`? 

```
pip install -U pip
```

**Comment by guiwork** [comment]
I was using the python-pip package from my Ubuntu system. I went ahead and removed that package and then used the get_pip.py script to get pip installed again. I had to install again the python2.7-dev package as my Python header files were removed. I then tried the command you suggested, followed by "sudo pip install jupyter_kernel_gateway" and it successfully installs.

Thanks

**Comment by parente** [comment]
Cool. Thanks for opening and reporting back.
