### ISSUE TITLE
Uncaught exception in /api/kernels/xxx/channels

### ISSUE THREAD

**Issue by fxlex** [jupyter/kernel_gateway#160]
I am trying to open a new session and send two commands to this session. The general error message is: ValueError: No JSON object could be decoded. Full log below.
```
[KernelGatewayApp] The Jupyter Kernel Gateway is running at: http://127.0.0.1:8888
...
[KernelGatewayApp] Starting kernel: [u'/Library/Frameworks/R.framework/Resources/bin/R', u'--slave', u'-e', u'IRkernel::main()', u'--args', u'/Users/alexanderpann/Library/Jupyter/runtime/kernel-f3f199d0-2160-4695-96a3-382acbb74147.json']
[KernelGatewayApp] Connecting to: tcp://127.0.0.1:52589
[KernelGatewayApp] Kernel started: f3f199d0-2160-4695-96a3-382acbb74147
[KernelGatewayApp] Kernel args: {'kernel_name': u'ir', 'cwd': u'/Users/alexanderpann'}
INFO:tornado.access:201 POST /api/sessions (127.0.0.1) 828.17ms
[KernelGatewayApp] Initializing websocket connection /api/kernels/f3f199d0-2160-4695-96a3-382acbb74147/channels
[KernelGatewayApp] WARNING | No session ID specified
[KernelGatewayApp] Requesting kernel info from f3f199d0-2160-4695-96a3-382acbb74147
[KernelGatewayApp] Connecting to: tcp://127.0.0.1:52586
[KernelGatewayApp] Received kernel info: {u'implementation': u'IRkernel', u'protocol_version': u'5.0', u'language_info': {u'mimetype': u'text/x-r-source', u'name': u'R', u'pygments_lexer': u'r', u'version': u'3.1.2', u'file_extension': u'.r', u'codemirror_mode': u'r'}, u'implementation_version': u'0.6', u'banner': u'R version 3.1.2 (2014-10-31)'}
[KernelGatewayApp] Opening websocket /api/kernels/f3f199d0-2160-4695-96a3-382acbb74147/channels
[KernelGatewayApp] Connecting to: tcp://127.0.0.1:52586
[KernelGatewayApp] Connecting to: tcp://127.0.0.1:52587
[KernelGatewayApp] Connecting to: tcp://127.0.0.1:52588
ERROR:tornado.application:Uncaught exception in /api/kernels/f3f199d0-2160-4695-96a3-382acbb74147/channels
Traceback (most recent call last):
  File "/Users/alexanderpann/anaconda/lib/python2.7/site-packages/tornado/websocket.py", line 417, in _run_callback
    callback(*args, **kwargs)
  File "/Users/alexanderpann/anaconda/lib/python2.7/site-packages/kernel_gateway/services/kernels/handlers.py", line 180, in on_message
    super(ZMQChannelsHandler, self).on_message(msg)
  File "/Users/alexanderpann/anaconda/lib/python2.7/site-packages/notebook/services/kernels/handlers.py", line 259, in on_message
    msg = json.loads(msg)
  File "/Users/alexanderpann/anaconda/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Users/alexanderpann/anaconda/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/alexanderpann/anaconda/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by parente** [comment]
Thanks for the report. Can you share what client you're using to trigger the error and what version of Jupyter notebook you also have installed (`pip freeze | grep notebook`)?

**Comment by fxlex** [comment]
The server and connecting java application (using web socket) are running on a Mac. The installed notebook version is notebook==4.2.0.

**Comment by parente** [comment]
I suspect that the client is not sending what the Jupyter protocol dictates. The exception is being thrown down in the notebook kernel handler code, not in any kernel gateway code, and I'm pretty certain the notebook 4.2 code works properly with IRKernel.

Can you try this experiment? Instead of running `jupyter kernelgateway` can you just run `jupyter notebook --allow_origin='*'` and point your client at that server instead? If it works there, then it's definitely a bug in kernel gateway. If not, then it's likely the client that is the culprit.

**Comment by fxlex** [comment]
Thank you for the help, I figured it out myself. The reason was malformed json send to the server.
