### ISSUE TITLE
Error with @jupyterlab/services 0.34.2 and notebook 4.3.0

### ISSUE THREAD

**Issue by nikitakit** [jupyter/kernel_gateway#204]
I just upgraded my notebook and `@jupyterlab/services` packages, and the gateway server is now throwing errors instead of running any code. (I'm using [nteract/hydrogen](https://github.com/nteract/hydrogen) to issue commands)

There seems to be a version mismatch of some sort, but I'm not sure how to resolve it.

Details:
```
$ jupyter kernelgateway --version
1.1.1
$ jupyter notebook --version
4.3.0
$ jupyter kernelgateway
[KernelGatewayApp] WARNING | Config option `list_kernels` not recognized by `KernelGatewayApp`.  Did you mean `max_kernels`?
[KernelGatewayApp] The Jupyter Kernel Gateway is running at: http://127.0.0.1:9890
[I 161210 16:06:32 web:1971] 200 GET /api/kernelspecs?1481414792420 (127.0.0.1) 430.08ms
[W 161210 16:06:32 web:1545] 403 GET /api/sessions?1481414792901 (127.0.0.1): Forbidden
[W 161210 16:06:32 web:1971] 403 GET /api/sessions?1481414792901 (127.0.0.1) 0.93ms
[KernelGatewayApp] WARNING | Sessions API changed, see updated swagger docs
[KernelGatewayApp] ERROR | Unhandled error in API request
Traceback (most recent call last):
  File "/Users/kitaev/anaconda/lib/python3.5/site-packages/notebook/base/handlers.py", line 481, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "/Users/kitaev/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/Users/kitaev/anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/kitaev/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kitaev/anaconda/lib/python3.5/site-packages/notebook/services/sessions/handlers.py", line 75, in post
    type=mtype))
  File "/Users/kitaev/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/Users/kitaev/anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/kitaev/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 270, in wrapper
    result = func(*args, **kwargs)
TypeError: create_session() got an unexpected keyword argument 'type'
[E 161210 16:06:33 web:1971] 500 POST /api/sessions?1481414793628 (127.0.0.1) 3.55ms
^C[KernelGatewayApp] Interrupted...
```

**Comment by parente** [comment]
To what version did you upgrade your notebook?

**Comment by parente** [comment]
Doh. Sorry. Output. 

Yes. 4.3.0 has a change in the session API that needs to be integrated here.

**Comment by parente** [comment]
Ref: #154

**Comment by parente** [comment]
Looks like another argument addition to the `SessionManager.create_session` like what happened in , #155 between notebook 4.1 and 4.2.

@minrk, I'm thinking that it makes sense to add `**kwargs` here to prevent future breakage instead of having a stricter dependency version spec setup.py from `notebook>=4.2.0,<=5.0.0` to `notebook==4.3.*`. Do you agree?

**Comment by minrk** [comment]
> I'm thinking that it makes sense to add **kwargs here to prevent future breakage

Yes, that seems like a good idea. I don't usually think of adding args as a breaking change, but of course it is for implementers of a spec. Sorry about that.

**Comment by parente** [comment]
Ref: https://github.com/nteract/hydrogen/pull/552

**Comment by parente** [comment]
@nikitakit Thanks for the report. I've loosened up the function specs and cut a 1.1.2 release with the fix. It's on pypi already and conda-forge should have it soon.
