### ISSUE TITLE
Duplicate message signature exception w/ notebook 5.0

### ISSUE THREAD

**Issue by parente** [jupyter/kernel_gateway#224]
Some kind of conflict with the new activity tracking API. Possible that KG is deserializing elsewhere for activity tracking or other purposes (notebook-http mode) and causing the jupyter_client session to think it's already seen the message.

```
Traceback (most recent call last):
  File "/Users/parente/miniconda3/envs/kernel-gateway-dev/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/Users/parente/miniconda3/envs/kernel-gateway-dev/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/parente/miniconda3/envs/kernel-gateway-dev/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/Users/parente/miniconda3/envs/kernel-gateway-dev/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/parente/miniconda3/envs/kernel-gateway-dev/lib/python3.5/site-packages/notebook/services/kernels/kernelmanager.py", line 220, in record_activity
    msg = kernel.session.deserialize(fed_msg_list)
  File "/Users/parente/miniconda3/envs/kernel-gateway-dev/lib/python3.5/site-packages/jupyter_client/session.py", line 853, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'50ee6f93c211428d751309f08f8795fce0028eeae09b82bb5cd82881278b0e73'
```

Ref: https://github.com/jupyter/notebook/issues/2150

**Comment by pooja-cactusglobal** [comment]
I am facing similar issue :
raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature:

Can you please help me out with a solution?
