### ISSUE TITLE
jupyter kernelgateway error

### ISSUE THREAD

**Issue by jarrekk** [jupyter/kernel_gateway#264]
hi, I install jupyter and kernel_gateway at Macos & python 3.6.3, but there is error when I run this:

```
•100% ➜ jupyter kernelgateway
Traceback (most recent call last):
  File "/Users/jack/.pyenv/py3.6.3/bin/jupyter-kernelgateway", line 11, in <module>
    sys.exit(launch_instance())
  File "/Users/jack/.pyenv/py3.6.3/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/jack/.pyenv/py3.6.3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
##
  File "/Users/jack/.pyenv/py3.6.3/lib/python3.6/site-packages/kernel_gateway/gatewayapp.py", line 345, in initialize
    self.init_http_server()
  File "/Users/jack/.pyenv/py3.6.3/lib/python3.6/site-packages/kernel_gateway/gatewayapp.py", line 477, in init_http_server
    self.http_server.listen(port, self.ip)
  File "/Users/jack/.pyenv/py3.6.3/lib/python3.6/site-packages/tornado/tcpserver.py", line 142, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/jack/.pyenv/py3.6.3/lib/python3.6/site-packages/tornado/netutil.py", line 156, in bind_sockets
    0, flags)):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

my `/etc/hosts/` file is :

```
•100% ➜ cat /etc/hosts
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost Jacks-MacBook-Pro.local Jacks-MacBook-Pro
255.255.255.255	broadcasthost
::1             localhost Jacks-MacBook-Pro.local Jacks-MacBook-Pro
```

I am not sure where I need to correct this. Many thanks if anyone can give me some help!

**Comment by rolweber** [comment]
I'm not sure if it's wise to define the same name for different IP addresses in /etc/hosts. But assuming that this is how the Mac is set up by default, it's probably OK.

Have you set any environment variables that start with KG_ and could interfere with default parameters?
http://jupyter-kernel-gateway.readthedocs.io/en/latest/config-options.html
If yes, try to unset them or override the environment by specifying command-line arguments.

**Comment by jarrekk** [comment]
@rolweber 
here is my env:
```
➜ env
TERM_SESSION_ID=w0t2p0:70AF5D1F-1446-40B1-BEA4-636634FA57F2
SSH_AUTH_SOCK=/private/tmp/com.xxx.launchd.fqHsjSJNZV/Listeners
Xxx_PubSub_Socket_Render=/private/tmp/com.xxx.launchd.dFlRZ7D9jN/Render
COLORFGBG=7;0
ITERM_PROFILE=Default
XPC_FLAGS=0x0
LANG=en_US.UTF-8
PWD=/Users/jack
SHELL=/bin/zsh
TERM_PROGRAM_VERSION=3.1.4
TERM_PROGRAM=iTerm.app
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
COLORTERM=truecolor
TERM=xterm-256color
HOME=/Users/jack
TMPDIR=/var/folders/tg/wqgcsyrn1pq8zbp61d_r8fvr0000gn/T/
USER=jack
XPC_SERVICE_NAME=0
LOGNAME=jack
__CF_USER_TEXT_ENCODING=0x0:0:0
ITERM_SESSION_ID=w0t2p0:70AF5D1F-1446-40B1-BEA4-636634FA57F2
SHLVL=1
OLDPWD=/Users/jack
ZSH=/Users/jack/.oh-my-zsh
PAGER=less
LESS=-R
LC_CTYPE=en_US.UTF-8
LSCOLORS=Gxfxcxdxbxegedabagacab
LS_COLORS=no=00:fi=00:di=01;34:ln=00;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=41;33;01:ex=00;32:ow=0;41:*.cmd=00;32:*.exe=01;32:*.com=01;32:*.bat=01;32:*.btm=01;32:*.dll=01;32:*.tar=00;31:*.tbz=00;31:*.tgz=00;31:*.rpm=00;31:*.deb=00;31:*.arj=00;31:*.taz=00;31:*.lzh=00;31:*.lzma=00;31:*.zip=00;31:*.zoo=00;31:*.z=00;31:*.Z=00;31:*.gz=00;31:*.bz2=00;31:*.tb2=00;31:*.tz2=00;31:*.tbz2=00;31:*.avi=01;35:*.bmp=01;35:*.fli=01;35:*.gif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mng=01;35:*.mov=01;35:*.mpg=01;35:*.pcx=01;35:*.pbm=01;35:*.pgm=01;35:*.png=01;35:*.ppm=01;35:*.tga=01;35:*.tif=01;35:*.xbm=01;35:*.xpm=01;35:*.dl=01;35:*.gl=01;35:*.wmv=01;35:*.aiff=00;32:*.au=00;32:*.mid=00;32:*.mp3=00;32:*.ogg=00;32:*.voc=00;32:*.wav=00;32:*.patch=00;34:*.o=00;32:*.so=01;35:*.ko=01;31:*.la=00;33
_=/usr/bin/env
```
I haven't seen params like `KG_*` 😔

**Comment by rolweber** [comment]
The environment looks OK. Other reports of the same error message hint at various kinds of networking problems. Here is one example:
https://stackoverflow.com/a/12102439

Here's another example, where the problem was reproduced without using Jupyter or Tornado at all:
https://github.com/tornadoweb/tornado/issues/1136#issuecomment-51281375

Maybe it helps when you specify the IP address explicitly?
```
jupyter kernelgateway --ip=127.0.0.1
```
That's the default anyway, so it _shouldn't_ make a difference, but I have no better ideas.
You could also try IPv6...
```
jupyter kernelgateway --ip=::1
```

**Comment by jarrekk** [comment]
@rolweber It works perfectly!
In my `jupyter_kernel_gateway_config.py`, i set **c.KernelGatewayApp.ip = '*'**, so it should be `0.0.0.0`, very professional 👍
