### ISSUE TITLE
Issue faced while doing the PySpark experiment

### ISSUE THREAD

**Issue by AnnamalaiVenugopal** [jupyter/kernel_gateway#269]
Traceback (most recent call last):
  File "C:\Users\avenugopal\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\avenugopal\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\avenugopal\Downloads\spark-2.2.0-bin-hadoop2.7\python\lib\pyspark.zip\pyspark\worker.py", line 216, in <module>
  File "C:\Users\avenugopal\Downloads\spark-2.2.0-bin-hadoop2.7\python\lib\pyspark.zip\pyspark\worker.py", line 202, in main
  File "C:\Users\avenugopal\Downloads\spark-2.2.0-bin-hadoop2.7\python\lib\pyspark.zip\pyspark\serializers.py", line 577, in read_int
EOFError

my script is:

```python
import sys
import os
import pyspark
from nltk.stem import SnowballStemmer
from nltk.corpus import wordnet as wn
from os import listdir
from os.path import isfile, join
from pyspark.sql.types import *

from pyspark.ml.feature import RegexTokenizer
from pyspark.sql.functions import udf
from pyspark.ml.feature import StopWordsRemover, CountVectorizer, IDF
from pyspark.ml.linalg import SparseVector, VectorUDT
lmtzr = SnowballStemmer("english")
import concurrent.futures

# Set the path for spark installation
# this is the path where you downloaded and uncompressed the Spark download
# Using forward slashes on windows, \\ should work too.
os.environ['SPARK_HOME'] = "C:/Users/avenugopal/Downloads/spark-2.2.0-bin-hadoop2.7/"
# Append the python dir to PYTHONPATH so that pyspark could be found
sys.path.append("C:/Users/avenugopal/Downloads/spark-2.2.0-bin-hadoop2.7/python/")
# Append the python/build to PYTHONPATH so that py4j could be found
sys.path.append('C:/Users/avenugopal/Downloads/spark-2.2.0-bin-hadoop2.7/python/build')
# try the import Spark Modules
try:
    from pyspark import SparkContext
    from pyspark import SparkConf
    from pyspark import SQLContext
    from pyspark.sql import SparkSession
    from pyspark.sql.functions import column

except ImportError as e:
    print("Error importing Spark Modules", e)
    sys.exit(1)

# Run a word count example on the local machine:

    # if len(sys.argv) != 2:
    #     print ( sys.stderr, "Usage: wordcount <file>")
    #     exit(-1)
conf = SparkConf()
conf.setMaster("local")
conf.setAppName("spark_wc").set("spark.driver.maxResultSize", "3g").set("spark.executor.memory" ,"3g");
sc = SparkContext(conf=conf)

sc.range(100)

my_path = "venv//reuters-extracted"
only_files = [f for f in listdir(my_path) if isfile(join(my_path, f))]
print(only_files)
schema = StructType([
    StructField("id", IntegerType(), True),
    StructField("sentence", StringType(), True),
])
rowList = []
index = 0
for file in enumerate(only_files):
    with open(os.path.join(my_path,file[1]), 'r') as my_file:
        data = my_file.read().replace('\n', '')
    rowList.append((index,data))
    index=index+1
spark = SparkSession.builder .appName("TokenizerExample").getOrCreate()
# $example on$
# sentenceDataFrame = spark.createDataFrame([
#     (0, "Hi I heard about Spark"),
#     (1, "I wish Java could use case classes"),
#     (2, "Logistic,regression,models,are,neat")
# ], ["id", "sentence"])
sentenceDataFrame=spark.createDataFrame(sc.parallelize(rowList),schema)
regexTokenizer = RegexTokenizer(inputCol="sentence", outputCol="words", pattern="[^a-zA-Z]")
# alternatively, pattern="\\w+", gaps(False)

countTokens = udf(lambda words: len(words), IntegerType())

regexTokenized = regexTokenizer.transform(sentenceDataFrame)

remover = StopWordsRemover(inputCol="words", outputCol="filtered")
filtered = remover.transform(regexTokenized)
filtered = filtered.drop("sentence").drop("words")

dataType = ArrayType(StringType(),False)
stemmingFn = udf(lambda words:stemmer(words),dataType)

def stemmer(words):
    stemmed_words = [lmtzr.stem(word) for word in words]
    return stemmed_words


stemmed = filtered.withColumn("stemmedWords", stemmingFn(column("filtered")))

stemmed.select("stemmedWords").show(truncate=False)

cv = CountVectorizer(inputCol="stemmedWords", outputCol="features")

model = cv.fit(stemmed)
result = model.transform(stemmed)
result.select("features").show(truncate=False)
vocabulary = model.vocabulary
print(len(vocabulary))

idf = IDF(inputCol="features", outputCol="IDF_features")
idfModel = idf.fit(result)
rescaledData = idfModel.transform(result)

rescaledData.select("IDF_features").show(truncate=False)


def filtering(vector):
    size = vector.size
    indices = vector.indices
    values = vector.values
    new_indices = []
    new_values = []
    for iterator, value in zip(indices,values):
        if value >= 0.8:
            new_indices.append(iterator)
            new_values.append(value)
    sparse_vector = SparseVector(size, new_indices, new_values)
    return sparse_vector


filterFn = udf(lambda vector: filtering(vector), VectorUDT())
filteredData = rescaledData.withColumn("filteredData", filterFn("IDF_features"))
filteredData = filteredData.drop("filtered");
filteredData.select("filteredData").show(truncate=False)


def token_extract(vector):
    indices = vector.indices
    tokens = []
    for iterator in indices:
        tokens.append(vocabulary[iterator])
    return tokens


token_extract_fn = udf(lambda vector: token_extract(vector),ArrayType(StringType()))

token_extracted_data = filteredData.withColumn("token_extracted_data",token_extract_fn("filteredData"))
token_extracted_data.select("token_extracted_data").show(truncate=False)

cv = CountVectorizer(inputCol="token_extracted_data", outputCol="newFeatures")

model = cv.fit(token_extracted_data)
result = model.transform(token_extracted_data)
result.select("newFeatures").show(truncate=False)
result=result.drop("filteredData")
vocabulary = model.vocabulary
print(len(vocabulary))


def hypernym_generation(token_array_a):
    token_array = token_array_a
    hypernym_dictionary = {}
    for token in token_array:
        # if token in hypernym_dictionary.keys():
        #     hypernym_dictionary[token].append(get_hypernyms(token))
        # else:
            hypernym_dictionary[token] = get_hypernyms(token)
    return hypernym_dictionary


def get_hypernyms(token):
    synsets = wn.synsets(token)
    hypernym_set = []
    # print(type(synsets))
    for synset in synsets:
        hypernyms = synset.hypernyms()
        if len(hypernyms) > 0:
            for hypernym in hypernyms:
                hypernym_set.append(hypernym.lemma_names()[0])
    return hypernym_set


print(get_hypernyms("cat"))
hypernym_fn = udf(lambda token_array: hypernym_generation(token_array), MapType(StringType(), ArrayType(StringType(),False),True))
hypernym_extracted_data = result.withColumn("hypernym_extracted_data", hypernym_fn(column("token_extracted_data")))
hypernym_extracted_data.select("hypernym_extracted_data").show(truncate=False)

sc.stop()
```

**Comment by rolweber** [comment]
What exactly are you trying to do? Use pyspark from a running kernel? Has the kernel been started with pyspark in the first place? Why are you trying to execute `runpy` when you already have a running Python environment?

If you want to use pyspark within a kernel, you should prepare the Spark configuration outside of Jupyter, and then prepare a "pyspark" kernel spec that uses pyspark instead of plain python to run your kernel.

**Comment by AnnamalaiVenugopal** [comment]
i am trying to implement an algorithm and am doing it with pycharm IDE.

Can you please give the "pyspark" kernel spec that uses pyspark ?

**Comment by rolweber** [comment]
I'm not familiar with pycharm IDE, maybe someone else can help.
The kernel spec would have to be written specifically for you environment.

**Comment by AnnamalaiVenugopal** [comment]
cool.. thanks for your time :-) @rolweber

**Comment by kevin-bates** [comment]
@AnnamalaiVenugopal - you might try taking a look at the [example kernelspecs](https://github.com/jupyter/enterprise_gateway/tree/master/etc/kernelspecs) provided by Enterprise Gateway.  These would require use of the EG process proxies, but they may give you hints of how to go about this in general.  

If you've moved on from this, we should probably close this issue.

**Comment by rolweber** [comment]
Closing as suggested by Kevin.
