### ISSUE TITLE
Allow access from remote hosts

### ISSUE THREAD

**Issue by kevin-bates** [jupyter/kernel_gateway#293]
As of [Notebook PR 3714](https://github.com/jupyter/notebook/pull/3714/) access from non-local hosts is being denied by default.  Since this is the primary functionality provided by Kernel Gateway, we should always enable the ability to provide access from remote hosts.  (The [same change](https://github.com/jupyter-incubator/enterprise_gateway/pull/386) was required in Enterprise Gateway.)

**Comment by rolweber** [comment]
The PR also removed Python 3.3 from the Travis CI configuration. I don't remember whether removing support for Python 3.3 was already discussed, but I'm all for it :-)

**Comment by kevin-bates** [comment]
Shoot - I'm sorry, I meant to include something like the following...

I've removed 3.3 from the Travis config since `pkg_resources` (via `setuptools`) no longer supports Python 3.3.  That update was merged late May and delivered in release 40.0.0 July 8th.
```
$ python --version
Python 3.3.6
$ pip --version
pip 8.1.2 from /home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages (python 3.3)
install.1
4.07s$ pip install --upgrade setuptools pip
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/ff/f4/385715ccc461885f3cedf57a41ae3c12b5fec3f35cce4c8706b1a112a133/setuptools-40.0.0-py2.py3-none-any.whl (567kB)
    100% |████████████████████████████████| 573kB 452kB/s 
Collecting pip
  Downloading https://files.pythonhosted.org/packages/0f/74/ecd13431bcc456ed390b44c8a6e917c1820365cbebcb6a8974d1cd045ab4/pip-10.0.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 1.1MB/s 
Installing collected packages: setuptools, pip
  Found existing installation: setuptools 18.0.1
    Uninstalling setuptools-18.0.1:
      Successfully uninstalled setuptools-18.0.1
  Found existing installation: pip 8.1.2
    Uninstalling pip-8.1.2:
      Successfully uninstalled pip-8.1.2
Successfully installed pip-7.1.2 setuptools-40.0.0
0.18s$ python setup.py bdist_wheel sdist
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from setuptools import setup
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/setuptools/__init__.py", line 12, in <module>
    import setuptools.version
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/pkg_resources/__init__.py", line 85, in <module>
    raise RuntimeError("Python 3.4 or later is required")
RuntimeError: Python 3.4 or later is required
```
