### ISSUE TITLE
Drop support for Python 3.3 in favor of 3.7

### ISSUE THREAD

**Issue by rolweber** [jupyter/kernel_gateway#295]
As documented in https://github.com/jupyter/kernel_gateway/issues/293#issuecomment-406281658, one of the dependencies of `setuptools` no longer supports Python 3.3.

With [Python 3.7.0](https://www.python.org/downloads/release/python-370/) officially released now, I suggest to drop support for Python 3.3. And we should enable Travis for Python 3.7.

**Comment by kevin-bates** [comment]
I definitely agree with dropping 3.3.  However, I believe we enabled 3.7 in our travis yaml for Enterprise Gateway and ran into some strange issues.  That may have been when 3.7 was on the cusp of being official.  I can't recall the issues but because we didn't have time to take a closer look, we backed out that update.  Not sure if KG will encounter similar issues, but wanted to share that experience with 3.7.

**Comment by kevin-bates** [comment]
I don't think support for Python 3.7 in travis is ready for prime time just yet.  When enabled, I get the following:
```
3.7 is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.7.tar.bz2
$ curl -sSf -o python-3.7.tar.bz2 ${archive_url}
curl: (22) The requested URL returned error: 403 Forbidden
Unable to download 3.7 archive. The archive may not exist. Please consider a different version.
```
This is backed up by this issue: https://github.com/travis-ci/travis-ci/issues/9815

However, using `- 3.7-dev` does work.  So I suppose we could move to that for now.

**Comment by dleen** [comment]
FYI: I'm running 3.7.2 and the tests all pass, although it exits with:
```
OK
Exception ignored in: <generator object NotebookAPIHandler._handle_request at 0x110b79840>
Traceback (most recent call last):
  File "/Users/davileen/Development/jupyter/kg-dev/kernel_gateway/notebook_http/handlers.py", line 226, in _handle_request
    self.response_future.set_result(None)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 688, in call_soon
    self._check_closed()
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <generator object NotebookAPIHandler._handle_request at 0x110c19660>
Traceback (most recent call last):
  File "/Users/davileen/Development/jupyter/kg-dev/kernel_gateway/notebook_http/handlers.py", line 226, in _handle_request
    self.response_future.set_result(None)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 688, in call_soon
    self._check_closed()
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```
but I think that's a known issue.

And the travis issue is resolved.

**Comment by rolweber** [comment]
@dleen Would you consider to submit another PR that adds Python 3.7 to Travis?
It's just another line here: https://github.com/jupyter/kernel_gateway/blob/master/.travis.yml#L3-L7

**Comment by dleen** [comment]
Done!
