### ISSUE TITLE
'Error seeding kernel memory'

### ISSUE THREAD

**Issue by robmarkcole** [jupyter/kernel_gateway#298]
On attempting to run a gateway it shutdowns after a second or so with the following:
```
(C:\ProgramData\Anaconda3) C:\Users\RCole\Documents\Bitbucket\robin_cole\Python_
Packages_Examples\jupyter_kernel_gateway>jupyter kernelgateway --KernelGatewayAp
p.api='kernel_gateway.notebook_http' --KernelGatewayApp.seed_uri='simple_test.ip
ynb'
[KernelGatewayApp] Kernel started: ad7811e6-20d8-4cc1-aca9-31f11c62235f
[KernelGatewayApp] Kernel shutdown: ad7811e6-20d8-4cc1-aca9-31f11c62235f
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\jupyter-kernelgateway-script.py", line
11, in <module>
    load_entry_point('jupyter-kernel-gateway', 'console_scripts', 'jupyter-kerne
lgateway')()
  File "c:\programdata\anaconda3\lib\site-packages\jupyter_core\application.py",
 line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\traitlets\config\application.
py", line 657, in launch_instance
    app.initialize(argv)
  File "c:\users\rcole\python\kernel_gateway-master\kernel_gateway\gatewayapp.py
", line 371, in initialize
    self.init_configurables()
  File "c:\users\rcole\python\kernel_gateway-master\kernel_gateway\gatewayapp.py
", line 425, in init_configurables
    self.personality.init_configurables()
  File "c:\users\rcole\python\kernel_gateway-master\kernel_gateway\notebook_http
\__init__.py", line 79, in init_configurables
    self.parent.kernel_manager
  File "c:\users\rcole\python\kernel_gateway-master\kernel_gateway\services\kern
els\pool.py", line 68, in __init__
    super(ManagedKernelPool, self).__init__(prespawn_count, kernel_manager)
  File "c:\users\rcole\python\kernel_gateway-master\kernel_gateway\services\kern
els\pool.py", line 30, in __init__
    self.kernel_manager.start_seeded_kernel()
  File "c:\users\rcole\python\kernel_gateway-master\kernel_gateway\services\kern
els\manager.py", line 72, in start_seeded_kernel
    return ioloop.IOLoop.current().run_sync(start)
  File "c:\programdata\anaconda3\lib\site-packages\tornado\ioloop.py", line 581,
 in run_sync
    return future_cell[0].result()
  File "c:\programdata\anaconda3\lib\site-packages\tornado\gen.py", line 1113, i
n run
    yielded = self.gen.send(value)
  File "c:\users\rcole\python\kernel_gateway-master\kernel_gateway\services\kern
els\manager.py", line 109, in start_kernel
    raise RuntimeError('Error seeding kernel memory', msg['content'])
RuntimeError: ('Error seeding kernel memory', {'status': 'error', 'traceback': [
'\x1b[1;31m---------------------------------------------------------------------
------\x1b[0m', '\x1b[1;31mNameError\x1b[0m                                 Trac
eback (most recent call last)', "\x1b[1;32m<ipython-input-3-275183ebc78c>\x1b[0m
 in \x1b[0;36m<module>\x1b[1;34m()\x1b[0m\n\x1b[1;32m----> 1\x1b[1;33m \x1b[1;32
mif\x1b[0m \x1b[1;34m'angle'\x1b[0m \x1b[1;32mnot\x1b[0m \x1b[1;32min\x1b[0m \x1
b[0margs\x1b[0m\x1b[1;33m:\x1b[0m\x1b[1;33m\x1b[0m\x1b[0m\n\x1b[0m\x1b[0;32m
  2\x1b[0m   \x1b[0mprint\x1b[0m\x1b[1;33m(\x1b[0m\x1b[0mjson\x1b[0m\x1b[1;33m.\
x1b[0m\x1b[0mdumps\x1b[0m\x1b[1;33m(\x1b[0m\x1b[1;33m{\x1b[0m\x1b[1;34m'converte
dAngle'\x1b[0m\x1b[1;33m:\x1b[0m \x1b[1;32mNone\x1b[0m\x1b[1;33m}\x1b[0m\x1b[1;3
3m)\x1b[0m\x1b[1;33m)\x1b[0m\x1b[1;33m\x1b[0m\x1b[0m\n\x1b[0;32m      3\x1b[0m \
x1b[1;32melse\x1b[0m\x1b[1;33m:\x1b[0m\x1b[1;33m\x1b[0m\x1b[0m\n\x1b[0;32m
4\x1b[0m   \x1b[1;31m# Note the [0] when retrieving the argument.\x1b[0m\x1b[1;3
3m\x1b[0m\x1b[1;33m\x1b[0m\x1b[0m\n\x1b[0;32m      5\x1b[0m   \x1b[1;31m# This i
s because you could potentially pass multiple angles.\x1b[0m\x1b[1;33m\x1b[0m\x1
b[1;33m\x1b[0m\x1b[0m\n", "\x1b[1;31mNameError\x1b[0m: name 'args' is not define
d"], 'ename': 'NameError', 'evalue': "name 'args' is not defined", 'engine_info'
: {'engine_uuid': '10b16946-f13a-4d54-9ad9-4dc3a6631cc1', 'engine_id': -1, 'meth
od': 'execute'}, 'execution_count': 3, 'user_expressions': {}, 'payload': []})
```

**Comment by kevin-bates** [comment]
i know very little about the notebook_http personality, but you have some cells denoted as `seed cells` and the execution of one of those code cells (performed at kernel startup), is returning a failed status, causing kernel-gateway to shutdown the kernel.

You can kinda pick through the color codes and see this is a `NameError: "name 'args' not defined"`.  

If the notebook works fine in normal modes (i.e., via the websocket-personality), then perhaps you've marked a cell as a _seed cell_ that is missing a dependency on a previous cell's execution (which is not marked as a seed cell).  (Note: this is just a hypothesis based on 5 minutes of reading about notebook_http.  Its not clear to me how a cell is denoted as a seed cell although I suspect it might be a cell where no `ResponseInfo` comment has been provided - from a quick code scan. )

**Comment by robmarkcole** [comment]
@kevin-bates you are correct, and the error is resolved when I place all of the contents in a single cell under the `# GET /convert` comment. 

I was following https://ndres.me/post/jupyter-notebook-rest-api/ btw

Thanks!

**Comment by kevin-bates** [comment]
@robmarkcole - thanks for the update and the link to the example.

Seems to me what is wanted here is for the `import` statements to be a _seed cell_, while the "convert" cell is not a seed cell - otherwise it gets run at startup (which is what you'd want for the `import` statements).

I think by decorating with "convert" cell with a `ResponseInfo` indicator, then it would not be a deemed a seed cell.  I'm just not sure how the `import` statements would be decorated such that they are a seed cell.

@parente - do you know what would be necessary to get the example text working as expected?
