### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by SamuBox** [jupyter/kernel_gateway#308]
Im constantly getting this when opening a notebook, Ubuntu 18 and python 3, looks like the kernel is always restarting

```
[I 11:22:56.100 NotebookApp] Adapting to protocol v5.1 for kernel 71892cba-9686-483f-99a7-0c1ddcf4292c
[E 11:22:56.101 NotebookApp] Uncaught exception GET /api/kernels/71892cba-9686-483f-99a7-0c1ddcf4292c/channels?session_id=53584C83FED6492A8DCC955FB1D368D8 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/kernels/71892cba-9686-483f-99a7-0c1ddcf4292c/channels?session_id=53584C83FED6492A8DCC955FB1D368D8', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/samuel/.local/lib/python3.6/site-packages/tornado/websocket.py", line 546, in _run_callback
        result = callback(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/notebook/services/kernels/handlers.py", line 258, in open
        super(ZMQChannelsHandler, self).open()
      File "/usr/lib/python3/dist-packages/notebook/base/zmqhandlers.py", line 168, in open
        self.send_ping, self.ping_interval, io_loop=loop,
    TypeError: __init__() got an unexpected keyword argument 'io_loop'
```

this is what i get when I type jupyter notebook, not sure if its normal, the 404 seems fishy

```
[I 11:22:22.870 NotebookApp] Serving notebooks from local directory: /home/samuel/.local/lib/python3.6/site-packages
[I 11:22:22.870 NotebookApp] 0 active kernels
[I 11:22:22.870 NotebookApp] The Jupyter Notebook is running at:
[I 11:22:22.870 NotebookApp] http://localhost:8888/?token=201cbff64e408111c669d3a1689e75319e869c2e6a51e8b7
[I 11:22:22.870 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 11:22:22.871 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=201cbff64e408111c669d3a1689e75319e869c2e6a51e8b7
[I 11:22:23.110 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[W 11:22:23.616 NotebookApp] 404 GET /static/components/moment/locale/es-es.js?v=20181003112222 (127.0.0.1) 9.78ms referer=http://localhost:8888/tree
[W 11:22:42.995 NotebookApp] 404 GET /static/components/moment/locale/es-es.js?v=20181003112222 (127.0.0.1) 1.41ms referer=http://localhost:8888/tree
```

**Comment by kevin-bates** [comment]
@SamuBox - thanks for posting the issue.  I have a couple comments/observations.
1. It looks like you're running Notebook w/o the nb2kg extension unless you didn't include entries immediately prior to `Serving notebooks from...`.  Otherwise, you'd have entries like these...
```
[I 23:04:11.938 NotebookApp] Loaded nb2kg extension
[I 23:04:11.938 NotebookApp] Overriding handler URLSpec('/api/kernelspecs/(?P<kernel_name>[\\w\\.\\-%]+)$', <class 'nb2kg.handlers.KernelSpecHandler'>, kwargs=None, name=None)
[I 23:04:11.938 NotebookApp] Overriding handler URLSpec('/api/kernelspecs$', <class 'nb2kg.handlers.MainKernelSpecHandler'>, kwargs=None, name=None)
[I 23:04:11.939 NotebookApp] Overriding handler URLSpec('/api/kernels/(?P<kernel_id>\\w+-\\w+-\\w+-\\w+-\\w+)/channels$', <class 'nb2kg.handlers.WebSocketChannelsHandler'>, kwargs=None, name=None)
[I 23:04:11.939 NotebookApp] Overriding handler URLSpec('/api/kernels/(?P<kernel_id>\\w+-\\w+-\\w+-\\w+-\\w+)/(?P<action>restart|interrupt)$', <class 'nb2kg.handlers.KernelActionHandler'>, kwargs=None, name=None)
[I 23:04:11.939 NotebookApp] Overriding handler URLSpec('/api/kernels/(?P<kernel_id>\\w+-\\w+-\\w+-\\w+-\\w+)$', <class 'nb2kg.handlers.KernelHandler'>, kwargs=None, name=None)
[I 23:04:11.940 NotebookApp] Overriding handler URLSpec('/api/kernels$', <class 'nb2kg.handlers.MainKernelHandler'>, kwargs=None, name=None)
```  
As a result, I'm not sure this issue is directed to the appropriate repository.

2. However, the `unexpected keyword argument 'io_loop'` exception indicates a version mismatch is at play here.  Tornado 5.0 changed the signature of various methods, so this implies you have a Tornado version >= 5.x and a Notebook version < 5.5.  Since its easier to move forward, I would recommend updating your Notebook version to >= 5.5 (after confirming you're using an updated Tornado).

Keep in mind that if you actually are using a Kernel Gateway, it limits Notebook versions to < 6.0.  Since, I believe, Notebook 6.0 is available, you might want to be explicit as to what version of Notebook to upgrade to.  Please note that that 6.0 limit is purely for safety reasons so as to not be surprised by possible breaking changes between gateway and notebook.  We will need to qualify the gateway against Notebook >= 6.0 at some point.

**Comment by SamuBox** [comment]
It was an outdated Notebook problem, updating made it work , thanks!

**Comment by kevin-bates** [comment]
Update: Looks like Notebook 6.0 is not available.  I had built an NB yesterday for something else and found the version to be 6.0.0, but that's just the dev version.  5.7.0 is the latest Notebook version and just because the dev version is 6.0.0.dev0 doesn't mean there won't be additional 5.x versions prior.
