### ISSUE TITLE
Timeout after 120 seconds in long job

### ISSUE THREAD

**Issue by argenisleon** [jupyter/kernel_gateway#328]
Hi,

I am executing a spark job through a jupyter gateway, but it timeout after 120 seconds. 

I can not find docs about how to set the timeout to a higher value. 

Any help?

**Comment by rolweber** [comment]
Have you investigated what exactly times out? Maybe there's a firewall inbetween that drops connections? Do you have logs that indicate the timeout is caused by the kernel gateway?

**Comment by argenisleon** [comment]
Thanks @rolweber 

I am getting this, but I am not sure if the problem is from the gateway

```
[E 191111 14:01:10 base_events:1285] Task exception was never retrieved
    future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/lib/python3.6/dist-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/websocket.py", line 1104, in wrapper
        await fut
    tornado.iostream.StreamClosedError: Stream is closed

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/websocket.py", line 1106, in wrapper
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 191111 14:01:10 base_events:1285] Task exception was never retrieved
    future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/lib/python3.6/dist-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/websocket.py", line 1104, in wrapper
        await fut
    tornado.iostream.StreamClosedError: Stream is closed

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/websocket.py", line 1106, in wrapper
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
```

**Comment by argenisleon** [comment]
Besides the JSON result, some logging info was printed and was causing the problem.
