### ISSUE TITLE
Event Loop Error

### ISSUE THREAD

**Issue by HCelion** [jupyter/kernel_gateway#332]
Hi, I am trying to connect to remotely start a jupyter kernel via an Atom text editor's Hydrogen package.
I set up a minimal environment and installed jupyter kernelgateway.

Passing the end points, my local machine did find the session and the available kernels.
However, upon connecting, kernel gateway starts spinning out of control. It seems that something with the asyncio is not working and the event loop is not properly managed.

Any idea what might have gone wrong? Thank you!

```
jupyter kernelgateway --port=9999 --ip=0.0.0.0
[KernelGatewayApp] Jupyter Kernel Gateway at http://0.0.0.0:9999
[I 200413 11:25:43 web:2250] 200 GET /api/kernelspecs?1586773544217 (10.0.102.88) 366.12ms
[W 200413 11:25:43 web:1786] 403 GET /api/sessions?1586773544591 (10.0.102.88): Forbidden
[W 200413 11:25:43 web:2250] 403 GET /api/sessions?1586773544591 (10.0.102.88) 2.18ms
[KernelGatewayApp] Kernel started: 2cb3b574-3a96-4d8c-a02b-f6a962b0f41f
[I 200413 11:25:45 web:2250] 201 POST /api/sessions?1586773546257 (10.0.102.88) 66.06ms
[I 200413 11:25:45 web:2250] 200 GET /api/kernels/2cb3b574-3a96-4d8c-a02b-f6a962b0f41f?1586773546327 (10.0.102.88) 1.34ms
[IPKernelApp] WARNING | Unknown error in handling startup files:
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    self.pre_handler_hook()
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 248, in pre_handler_hook
    self.saved_sigint_handler = signal(SIGINT, default_int_handler)
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    self.pre_handler_hook()
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 248, in pre_handler_hook
    self.saved_sigint_handler = signal(SIGINT, default_int_handler)
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
ERROR:tornado.application:Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x7fdd2cfe66a8>)
Traceback (most recent call last):
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 542, in <lambda>
    self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    self.pre_handler_hook()
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 248, in pre_handler_hook
    self.saved_sigint_handler = signal(SIGINT, default_int_handler)
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
Traceback (most recent call last):
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 149, in start
    self.asyncio_loop.run_forever()
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/asyncio/base_events.py", line 408, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
[KernelGatewayApp] KernelRestarter: restarting kernel (1/5), new random ports
[IPKernelApp] WARNING | Unknown error in handling startup files:
Traceback (most recent call last):
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 149, in start
    self.asyncio_loop.run_forever()
  File "/home/kingla/.conda/envs/test-env/lib/python3.6/asyncio/base_events.py", line 408, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
[KernelGatewayApp] KernelRestarter: restarting kernel (2/5), new random ports
^C[KernelGatewayApp] Interrupted...
[KernelGatewayApp] Kernel shutdown: 2cb3b574-3a96-4d8c-a02b-f6a962b0f41f

```

My installed packages are

```
_libgcc_mutex             0.1                        main    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.4              pyh9f0ad1d_0    conda-forge
certifi                   2016.2.28                py36_0
certifi                   2020.4.5.1                <pip>
chardet                   3.0.4                     <pip>
cycler                    0.10.0                    <pip>
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3             py36h9f0ad1d_1001    conda-forge
idna                      2.9                       <pip>
importlib-metadata        1.6.0            py36h9f0ad1d_0    conda-forge
importlib_metadata        1.6.0                         0    conda-forge
ipykernel                 4.6.1                    py36_0
ipython                   7.13.0           py36h9f0ad1d_2    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.16.0           py36h9f0ad1d_1    conda-forge
jinja2                    2.11.1                     py_0    conda-forge
json5                     0.9.0                      py_0    conda-forge
jsonschema                3.2.0            py36h9f0ad1d_1    conda-forge
jupyter-kernel-gateway    2.4.0                     <pip>
jupyter_client            6.1.2                      py_0    conda-forge
jupyter_core              4.6.3            py36h9f0ad1d_1    conda-forge
jupyterlab                2.1.0                      py_0    conda-forge
jupyterlab_server         1.0.7                      py_0    conda-forge
kiwisolver                1.2.0                     <pip>
libgcc-ng                 9.2.0                hdf63c60_0    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
markupsafe                1.1.1            py36h8c4c3a4_1    conda-forge
matplotlib                3.2.1                     <pip>
mistune                   0.8.4           py36h8c4c3a4_1001    conda-forge
nbconvert                 5.6.1            py36h9f0ad1d_1    conda-forge
nbformat                  5.0.4                      py_0    conda-forge
nest-asyncio              1.3.2                     <pip>
notebook                  6.0.3                    py36_0    conda-forge
numpy                     1.18.2                    <pip>
openssl                   1.0.2l                        0
pandoc                    2.9.2                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.6.2                      py_0    conda-forge
pexpect                   4.8.0            py36h9f0ad1d_1    conda-forge
pickleshare               0.7.5           py36h9f0ad1d_1001    conda-forge
pip                       9.0.1                    py36_1
prometheus_client         0.7.1                      py_0    conda-forge
prompt-toolkit            3.0.5                      py_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pyparsing                 2.4.7                     <pip>
pyrsistent                0.16.0           py36h8c4c3a4_0    conda-forge
python                    3.6.2                         0
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
pyzmq                     19.0.0           py36h9947dbf_1    conda-forge
readline                  6.2                           2
requests                  2.23.0                    <pip>
send2trash                1.5.0                      py_0    conda-forge
setuptools                36.4.0                   py36_1
six                       1.14.0                     py_1    conda-forge
sqlite                    3.13.0                        0
terminado                 0.8.3            py36h9f0ad1d_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tk                        8.5.18                        0
tornado                   6.0.4            py36h8c4c3a4_1    conda-forge
traitlets                 4.3.3            py36h9f0ad1d_1    conda-forge
urllib3                   1.25.8                    <pip>
wcwidth                   0.1.9              pyh9f0ad1d_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.29.0                   py36_0
xz                        5.2.3                         0
zeromq                    4.3.2                he1b5a44_2    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11                        0

```

**Comment by HCelion** [comment]
I had to update ipykernel to version 4.8.1 and the issue resolved.
