### ISSUE TITLE
Issues with jinja2_env

### ISSUE THREAD

**Issue by camer314** [jupyter/kernel_gateway#355]
I have been using the @jupyterhub\services JavaScript SDK to communicate with kernels by starting a notebook.

I was reading about the kernel gateway which is an alternate way to access kernels without a UI, which seems perfect. However I installed the latest kernel_gateway (2.4.3) and straight away am receiving the below error which renders the gateway inoperable. 

There seems to be some history with this error (https://github.com/jupyter/kernel_gateway/issues/71) and (https://github.com/jupyter/kernel_gateway/issues/99) but these are both from 2016.

Is this a recurrence of the issue or has it never been fixed?

[I 210417 15:35:47 web:2243] 200 GET /api/kernels?1618637747393 (127.0.0.1) 0.00ms
[E 210417 15:35:47 web:1219] Uncaught exception in write_error
    Traceback (most recent call last):
      File "c:\users\camer314\appdata\local\continuum\anaconda3\envs\azureml\lib\site-packages\tornado\web.py", line 1217, in send_error
        self.write_error(status_code, **kwargs)
      File "c:\users\camer314\appdata\local\continuum\anaconda3\envs\azureml\lib\site-packages\notebook\base\handlers.py", line 585, in write_error
        html = self.render_template('%s.html' % status_code, **ns)
      File "c:\users\camer314\appdata\local\continuum\anaconda3\envs\azureml\lib\site-packages\notebook\base\handlers.py", line 515, in render_template
        template = self.get_template(name)
      File "c:\users\camer314\appdata\local\continuum\anaconda3\envs\azureml\lib\site-packages\notebook\base\handlers.py", line 511, in get_template
        return self.settings['jinja2_env'].get_template(name)
    **KeyError: 'jinja2_env'**

**Comment by camer314** [comment]
Actually having read this [(https://github.com/jupyter/kernel_gateway/issues/233)] it gave me a clue that for tokens the WS must receive them as a query parameter so I modified my server connection object to honour that and now its working as expected.
